name: dart_rss
version: 1.0.1+1
description: dart-rss is a rss parser for RSS1.0/RSS2.0/Atom. It also support Dublin-Core, Content, Syndication additional modules. This libary is forked from webfeed(https://github.com/witochandra/webfeed).
homepage: https://github.com/sudame/dart-rss
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  xml: ^3.0.0
  http: ^0.11.0
  meta: ^1.0.0
  intl: any

dev_dependencies:
  test: ^1.0.0
